# To run pre-commit hooks, first install pre-commit:
# - `pip install pre-commit==${PRE_COMMIT_VERSION}`
#
# Then, run the following command to install the git hook scripts:
# - `pre-commit install`
# You can run all configured hooks against all files with:
# - `pre-commit run --all-files`
# To manually run a specific hook, use:
# - `pre-commit run <hook_id> --all-files`
# To run the hooks against only the staged files, use:
# - `pre-commit run`
repos:
  - repo: local
    hooks:
      - id: fix-include-style
        name: fix include style
        entry: ./bin/pre-commit/fix_include_style.py
        language: python
        types_or: [c++, c]
        exclude: ^include/xrpl/protocol_autogen/(transactions|ledger_entries)/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=400, --enforce-all]
      - id: check-executables-have-shebangs
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
        args: [--assume-in-merge]

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: dd18dad857d6133e90bbe478f4f2f22ec0030269 # frozen: v22.1.5
    hooks:
      - id: clang-format
        args: [--style=file]
        types_or: [c++, c, proto]
        exclude: ^include/xrpl/protocol_autogen/(transactions|ledger_entries)/
